### PR TITLE
Remove exit(1) when no files found to scan

### PR DESCRIPTION
**Pull request by Janey2022**

### CODE REVIEW

**Comment by Janey2022** [comment]
With the origin logic, if I run it in the cases that contains several dirs, it will break when found one has no matched file to scan.

**Comment by Janey2022** [comment]
It seems not a good approach. But still need to handle the issue when the loop exit in some cases.

**Comment by FelipeNasci** [comment]
How about throwing an exception in this case?

That way, we can catch the error with a `try{} catch(){}`

**Comment by Janey2022** [comment]
> How about throwing an exception in this case?
> 
> That way, we can catch the error with a `try{} catch(){}`

No, try catch can't catch process.exit(1).

**Review by FelipeNasci — APPROVED** [review]

**Comment by gyfchong** [comment]
Fixes https://github.com/moroshko/react-scanner/issues/68

**Review by JulianNymark — APPROVED** [review]

**Pull request merged**
