### PR TITLE
feat: allow running programmatically

### LINKED ISSUE #45: feature request: pass config options by parameter vs. file
first of all thanks for publishing this great library. I was about to write something on top of babel-traverse instead and this was a huge time-saver.

it's possible I missed some documentation on this, but to run react-scanner on a number of different component libraries (think a multi-brand or multi-platform design system), or with different config options on the same library to compare the data. in order to do this, I am writing a number of config files on the fly, and running react-scanner a number of times. even if react-scanner doesn't get a full API, being able to pass options via command line argument would be an improvement as well. 

let me know if I overlooked anything in my thinking about this. if you like this idea, it's possible I could contribute to a PR.

thanks!

### PR DESCRIPTION
**Pull request by mihkeleidast**
Resolves #45.

We have this need as well, currently we're setting some process.env variables dynamically to change the config on the go. Running programmatically would make the code much easier to follow.

### CODE REVIEW

**Comment by moroshko** [comment]
Thanks for this @mihkeleidast! 
Can we return the output when `outputTo` is not specified so one could process the results?
```
const output = await scanner.run(config)
```

**Comment by mihkeleidast** [comment]
@moroshko thanks for the feedback, I added returning the output from the function, plus a couple of tests as well. The CI seems to be failing on test coverage, though in my machine it succeeds - any idea what's up with that?

**Comment by mihkeleidast** [comment]
Seems like CI runs on Node 12, if I use it locally, it also fails on some weird lines, like the final `}` of the run function, which I do not really know how to fix. It does not seem to fail on Node 14. As Node 12 is EOL, could we update CI to use Node 14 instead?

**Comment by moroshko** [comment]
Sure, feel free to upgrade to node 14. I'll be fine with node 16 as well.

**Comment by mihkeleidast** [comment]
@moroshko done, update to Node 16, all green now!

**Comment by moroshko** [comment]
Published as 1.1.0.
Thanks @mihkeleidast for your contribution!

**Pull request merged**
